project_id = "gvhwsdctigkwwimbbyro"

[functions.ai-resume-analyzer]
verify_jwt = false

[functions.ai-mock-interview]
verify_jwt = false

[functions.ai-job-description]
verify_jwt = false

[functions.ai-aptitude-test]
verify_jwt = false

[functions.pdf-to-mcq]
verify_jwt = false
